<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net70</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Certificados\alias.p12" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Certificados\alias.p12">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="7.0.1" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.8.*" />
    <PackageReference Include="System.ServiceModel.Federation" Version="4.8.*" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.*" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.8.*" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.8.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Molinos.Scato.API.CrossCutting.Common\Molinos.Scato.API.CrossCutting.Common.csproj" />
    <ProjectReference Include="..\Molinos.Scato.API.Infrastructure.Service.Intefaces\Molinos.Scato.API.Infrastructure.Service.Interfaces.csproj" />
  </ItemGroup>

</Project>
