<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net70</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Molinos.Scato.API.Application.Implementation\Molinos.Scato.API.Application.Implementation.csproj" />
    <ProjectReference Include="..\Molinos.Scato.API.Application.Interfaces\Molinos.Scato.API.Application.Interfaces.csproj" />
    <ProjectReference Include="..\Molinos.Scato.API.CrossCutting.IoC\Molinos.Scato.API.CrossCutting.IoC.csproj" />
    <ProjectReference Include="..\Molinos.Scato.API.Infrastructure.Repository.Implementation\Molinos.Scato.API.Infrastructure.Repository.Implementation.csproj" />
  </ItemGroup>

</Project>
