<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net70</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Core\Implementation\**" />
    <EmbeddedResource Remove="Core\Implementation\**" />
    <None Remove="Core\Implementation\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Molinos.Scato.API.CrossCutting.DTO\Molinos.Scato.API.CrossCutting.DTO.csproj" />
    <ProjectReference Include="..\Molinos.Scato.API.CrossCutting.IoC\Molinos.Scato.API.CrossCutting.IoC.csproj" />
    <ProjectReference Include="..\Molinos.Scato.API.Infrastructure.Repository.Entities\Molinos.Scato.API.Infrastructure.Repository.Entities.csproj" />
    <ProjectReference Include="..\Molinos.Scato.API.Infrastructure.Repository.Interfaces\Molinos.Scato.API.Infrastructure.Repository.Interfaces.csproj" />
  </ItemGroup>

</Project>
