<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net70</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Molinos.Scato.API.Application.Interfaces\Molinos.Scato.API.Application.Interfaces.csproj" />
    <ProjectReference Include="..\Molinos.Scato.API.CrossCutting.IoC\Molinos.Scato.API.CrossCutting.IoC.csproj" />
    <ProjectReference Include="..\Molinos.Scato.API.Infrastructure.Repository.Interfaces\Molinos.Scato.API.Infrastructure.Repository.Interfaces.csproj" />
    <ProjectReference Include="..\Molinos.Scato.API.Infrastructure.Service.Implementation\Molinos.Scato.API.Infrastructure.Service.Implementation.csproj" />
  </ItemGroup>

</Project>
